import test from 'node:test';
import assert from 'node:assert/strict';
import {createActivityTracker} from '../adapters/harness/activity.mjs';
function chat({id=1,closed=false,reason='completed',calls=[],nodes=[]}={}) {
 const turn={turn:id,status:closed?'closed':'open',start:{seq:id*100},steps:[{step:1,status:closed?'closed':'open',data:new Map()}]};
 if(closed)turn.end={seq:id*100+99,data:{turn:id,reason:typeof reason==='string'?{kind:reason}:reason}};
 return {timeline:{turnOrder:[id],turns:new Map([[id,turn]])},legacy:{runningCalls:calls,nodes}};
}
function harness(){const states=[],timers=new Map(),delays=[],callbacks=[];let serial=0;const tracker=createActivityTracker(s=>states.push(s),{schedule(fn,ms){const id=++serial;timers.set(id,fn);callbacks.push(fn);delays.push(ms);return id;},cancel(id){timers.delete(id);}});return{tracker,states,timers,delays,callbacks,update(session={running:true},view=chat(),context={},status={},id='one'){tracker.update(id,session,status,view,context);},fire(){for(const[id,fn]of [...timers]){timers.delete(id);fn();}}};}
const entry=(type,seq,data)=>({event:{type,seq,data}});
function window(entries,revision=0,change={kind:'replace',entries}){return{entries,revision,change};}
function append(prior,...entries){return window([...prior.entries,...entries],prior.revision+1,{kind:'append',entries});}
const projection=values=>({sessions:{byId:{},projectionsBySession:{one:{values}}}});
const call={turn:1,step:1,phase:'start',callId:'bash'};

test('fresh canonical tool failure reacts four seconds then restores current work and never replays',()=>{const h=harness();let events=window([]);h.update({running:true},chat({calls:[call]}),{events});events=append(events,entry('tool/result',102,{turn:1,step:1,message:{source:{callId:'bash'},isError:true}}));h.update({running:true},chat(),{events});assert.equal(h.states.at(-1),'error');assert.ok(h.delays.at(-1)>=4000);h.update({running:true},chat({calls:[{...call,callId:'next'}]}),{events});assert.equal(h.states.at(-1),'error');h.fire();assert.equal(h.states.at(-1),'working');h.update({running:true},chat(),{events});assert.equal(h.states.at(-1),'thinking');assert.equal(h.timers.size,0);});
test('cancelled tool results and nonzero output decoration do not become errors',()=>{for(const result of [{isError:true,error:{code:'ABORTED'}},{isError:false,content:[{text:'exit code: 1'}]}]){const h=harness();let events=window([]);h.update({running:true},chat({calls:[call]}),{events});events=append(events,entry('tool/result',102,{turn:1,step:1,message:{source:{callId:'bash'},...result},error:result.error}));h.update({running:true},chat(),{events});assert.equal(h.states.at(-1),'thinking');assert.equal(h.timers.size,0);}});
test('nested PTC failures correlate the observed root call without guessing tool names',()=>{const h=harness();let events=window([]);h.update({running:true},chat({calls:[call]}),{events});events=append(events,entry('tool/ptc-dispatch',102,{rootCallId:'bash',subCallId:'sub',isError:true,error:{code:'EXEC_FAILED'}}));h.update({running:true},chat({calls:[call]}),{events});assert.equal(h.states.at(-1),'error');});
test('old baseline tool failures and failures from another turn are ignored',()=>{const h=harness();let events=window([entry('tool/result',80,{turn:0,message:{isError:true,source:{callId:'old'}}})]);h.update({running:true},chat({calls:[call]}),{events});assert.equal(h.states.at(-1),'working');events=append(events,entry('tool/result',102,{turn:0,message:{isError:true,source:{callId:'old'}}}));h.update({running:true},chat({calls:[call]}),{events});assert.equal(h.states.at(-1),'working');});
test('owned job failure reacts; historical, global and dropped roster cannot imply failure',()=>{const h=harness();h.update({running:true},chat(),{jobs:[{id:'old',owner:'one',status:'failed'},{id:'global',status:'running'}]});assert.equal(h.states.at(-1),'thinking');h.update({running:true},chat(),{jobs:[{id:'new',owner:'one',status:'running'}]});assert.equal(h.states.at(-1),'working');h.update({running:true},chat(),{jobs:[{id:'new',owner:'one',status:'failed'}]});assert.equal(h.states.at(-1),'error');h.fire();assert.equal(h.states.at(-1),'thinking');h.update({running:true},chat(),{jobs:undefined});h.update({running:true},chat(),{jobs:[{id:'new',owner:'one',status:'failed'}]});assert.equal(h.states.at(-1),'thinking','source readmission is a baseline');});
test('global ownerless jobs do not prevent observed whole-turn completion',()=>{const h=harness();h.update();h.update({running:false},chat({closed:true}),{jobs:[{id:'global',status:'running'}]});assert.equal(h.states.at(-1),'complete');});
test('whole-turn error wins over an owned live job and persists until new task',()=>{const h=harness();h.update();h.update({running:false},chat({closed:true,reason:'error'}),{jobs:[{id:'job',owner:'one',status:'running'}]});assert.equal(h.states.at(-1),'error');h.update({running:false},chat({closed:true,reason:'error'}));assert.equal(h.states.at(-1),'error');assert.equal(h.timers.size,0);h.update({running:true},chat({id:2}));assert.equal(h.states.at(-1),'thinking');});
test('historical latest whole-turn error is visible without celebration',()=>{for(const reason of ['error','max-tokens']){const h=harness();h.update({running:false},chat({closed:true,reason}));assert.equal(h.states.at(-1),'error');assert.equal(h.timers.size,0);}});
test('aborted and interrupted observed turns stop without celebration; forked is history',()=>{for(const reason of ['aborted','interrupted','forked']){const h=harness();h.update();h.update({running:false},chat({closed:true,reason}));assert.equal(h.states.at(-1),reason==='forked'?'idle':'stopped');assert.equal(h.timers.size,0);}});
test('signed-out hook cancellation is disconnected, not a successful task',()=>{const h=harness();h.update();h.update({running:false},chat({closed:true,reason:{kind:'aborted',reason:{kind:'hook',reason:'deepseek-account/signed-out'}}}));assert.equal(h.states.at(-1),'disconnected');});
test('rejected first send and active open failure are visible despite stale busy flags',()=>{const h=harness();h.update({running:false,awaitingFirstTurn:true,promptError:{op:'send',error:{code:'FAIL'}}},undefined);assert.equal(h.states.at(-1),'error');const g=harness();g.update();g.update({running:true,openState:'error',openError:{code:'FAIL'}},chat());assert.equal(g.states.at(-1),'error');});
test('fresh stop RPC or agent errors react while stale prior errors do not hide running',()=>{const h=harness();const old={op:'stop',error:{code:'OLD'}};h.update({running:true,promptError:old},chat({calls:[call]}));assert.equal(h.states.at(-1),'working');h.update({running:true,promptError:{op:'stop',error:{code:'NOW'}}},chat({calls:[call]}));assert.equal(h.states.at(-1),'error');h.fire();assert.equal(h.states.at(-1),'working');h.update({running:true,lastAgentError:'Remote session fault'},chat({calls:[call]}));assert.equal(h.states.at(-1),'error');});
test('explicit compaction failure and manual error outcome react without making a terminal error',()=>{const h=harness();let events=window([]);h.update({running:true},chat(),{events});events=append(events,entry('compaction/start',102,{turn:1,compactionId:'c'}));h.update({running:true},chat(),{events});assert.equal(h.states.at(-1),'compacting');events=append(events,entry('compaction/end',103,{turn:1,compactionId:'c',error:'Failure chain'}));h.update({running:true},chat(),{events});assert.equal(h.states.at(-1),'error');h.fire();assert.equal(h.states.at(-1),'thinking');events=append(events,entry('command/run',104,{commandId:'cmd',name:'compact'}));h.update({running:true},chat(),{events});events=append(events,entry('command/done',105,{commandId:'cmd',kind:'error',text:'Not parsed'}));h.update({running:true},chat(),{events});assert.equal(h.states.at(-1),'error');});
test('durable assistant settlement inserted below the watermark still reacts once',()=>{const h=harness();let events=window([]);h.update({running:true},chat(),{events});events=append(events,entry('assistant/live-chunk',110,{turn:1,step:1,chunk:{type:'text-delta',text:'reply'}}));h.update({running:true},chat(),{events});const failure=entry('assistant/attempt',103,{turn:1,step:1,stream:[{type:'chunk',chunk:{type:'finish',reason:{kind:'error',failure:{code:'REQUEST'}}}}]});events=window([failure,...events.entries],2,{kind:'settle-assistant',attemptId:'attempt',entry:failure});h.update({running:true},chat(),{events});assert.equal(h.states.at(-1),'error');h.fire();assert.equal(h.states.at(-1),'thinking');h.update({running:true},chat(),{events});assert.equal(h.timers.size,0);});
test('coalesced assistant finish failure is observed but cancelled finish is not an error',()=>{for(const kind of ['error','max-tokens','aborted']){const h=harness();const prior=window([]);h.update({running:true},chat(),{events:prior});const failure=entry('assistant/live-chunk',102,{turn:1,step:1,attemptId:'a',chunk:{type:'finish',reason:{kind}}});h.update({running:true},chat(),{events:window([failure],3,{kind:'append',entries:[]})});assert.equal(h.states.at(-1),kind==='aborted'?'thinking':'error');}});
test('historical review is not waiting; hidden live open question is waiting',()=>{const h=harness();h.update({running:true},chat({calls:[call]}),{}, {pendingInteraction:{kind:'question',review:{answers:[]},callId:'old'}});assert.equal(h.states.at(-1),'working');h.update({running:true},chat({calls:[call]}),projection({userQuestions:{active:[{callId:'bash',state:'open'}]}}));assert.equal(h.states.at(-1),'waiting');h.update({running:true},chat({calls:[call]}),projection({userQuestions:{active:[{callId:'old',state:'open'}]}}));assert.equal(h.states.at(-1),'working');});
test('continued question only asks attention while idle and ignores an already queued reply',()=>{const h=harness();const values={userQuestions:{active:[{callId:'bash',state:'continued'}]}};h.update({running:true},chat({calls:[call]}),projection(values));assert.equal(h.states.at(-1),'working');h.update({running:false},chat(),projection(values));assert.equal(h.states.at(-1),'waiting');h.update({running:false},chat(),projection({...values,inbox:{'next-step':[{source:{kind:'user-question-reply',callId:'bash'}}]}}));assert.equal(h.states.at(-1),'queued');});
test('real goal pause remains paused through cancellation; old paused goal does not mask a new manual turn',()=>{const h=harness();h.update({running:true},chat(),projection({goal:{goal:{id:'g',phase:'active'}}}));h.update({running:true},chat(),projection({goal:{goal:{id:'g',phase:'paused'}}}));assert.equal(h.states.at(-1),'paused');h.update({running:false},chat({closed:true,reason:'aborted'}),projection({goal:{goal:{id:'g',phase:'paused'}}}));assert.equal(h.states.at(-1),'paused');h.update({running:true},chat({id:2}),projection({goal:{goal:{id:'g',phase:'paused'}}}));assert.equal(h.states.at(-1),'thinking');});
test('goal blocked and turn policy block are explicit attention states, not errors',()=>{const h=harness();h.update({running:false},undefined,projection({goal:{goal:{phase:'blocked'}}}));assert.equal(h.states.at(-1),'blocked');const g=harness();g.update();g.update({running:false},chat({closed:true,reason:'blocked'}));assert.equal(g.states.at(-1),'blocked');});
test('connection source maps only real states and waiting takes priority',()=>{const h=harness();h.update({running:true},chat(),{connection:{state:'connecting'}});assert.equal(h.states.at(-1),'connecting');h.update({running:true},chat(),{connection:{state:'disconnected'}});assert.equal(h.states.at(-1),'disconnected');h.update({running:true},chat(),{connection:{state:'disconnected'}},{pendingInteraction:{kind:'approval',id:'a'}});assert.equal(h.states.at(-1),'waiting');h.update({running:true},chat(),{connection:{state:undefined}});assert.equal(h.states.at(-1),'thinking');});
test('queued native inbox and local pending submission are not invented active work',()=>{const h=harness();h.update({running:false},undefined,projection({inbox:{'next-turn':[{id:'m'}]}}));assert.equal(h.states.at(-1),'queued');h.update({running:false,pendingSubmissions:[{requestId:'r',placement:'queued'}]},undefined);assert.equal(h.states.at(-1),'queued');h.update({running:true},chat(),projection({inbox:{'next-turn':[{id:'m'}]}}));assert.equal(h.states.at(-1),'thinking');});
test('pulse callbacks cannot leak across a new task, session or disposal',()=>{for(const action of ['task','session','dispose']){const h=harness();let events=window([]);h.update({running:true},chat({calls:[call]}),{events});events=append(events,entry('tool/result',102,{turn:1,message:{source:{callId:'bash'},isError:true}}));h.update({running:true},chat(),{events});assert.equal(h.states.at(-1),'error');const callback=h.callbacks.at(-1);if(action==='dispose')h.tracker.dispose();else h.update({running:true},chat({id:2}),{}, {},action==='session'?'two':'one');const count=h.states.length;callback();assert.equal(h.states.length,count);assert.equal(h.timers.size,0);}});
test('empty trailing output blocks do not claim answering or hide meaningful text',()=>{const h=harness();const view=chat();view.timeline.turns.get(1).steps[0].data.set('assistant-step',{status:'running',turn:1,step:1,blocks:[{kind:'text',text:'reply'},{kind:'reasoning',text:'  '}]});h.update({running:true},view);assert.equal(h.states.at(-1),'answering');});

test('completion hold cannot override a later truthful connection phase',()=>{const h=harness();h.update();const closed=chat({closed:true});h.update({running:false},closed);assert.equal(h.states.at(-1),'complete');h.update({running:false},closed,{connection:{state:'connecting'}});assert.equal(h.states.at(-1),'connecting');h.fire();assert.equal(h.states.at(-1),'connecting');});
test('roster disappearance alone is unknown, but an observed completed turn proves main-turn completion',()=>{const h=harness();h.update({running:true},chat(),{jobs:[]});h.update({running:true},chat(),{jobs:[{id:'j',owner:'one',status:'running'}]});h.update({running:false},chat(),{jobs:undefined});assert.notEqual(h.states.at(-1),'complete');assert.equal(h.timers.size,0);h.update({running:false},chat({closed:true}),{jobs:undefined});assert.equal(h.states.at(-1),'complete');});
test('current transcript submission admits a fresh task before turn/start instead of retaining old error',()=>{const h=harness();const closed=chat({closed:true,reason:'error'});h.update({running:false},closed);assert.equal(h.states.at(-1),'error');h.update({running:false,pendingSubmissions:[{requestId:'new',placement:'transcript'}]},closed);assert.equal(h.states.at(-1),'queued');});
test('a new explicit goal completion is celebrated once while historic complete is not',()=>{const h=harness();h.update({running:false},undefined,projection({goal:{goal:{id:'g',phase:'active'}}}));h.update({running:false},undefined,projection({goal:{goal:{id:'g',phase:'complete'}}}));assert.equal(h.states.at(-1),'complete');h.fire();assert.equal(h.states.at(-1),'idle');const g=harness();g.update({running:false},undefined,projection({goal:{goal:{id:'g',phase:'complete'}}}));assert.equal(g.states.at(-1),'idle');});

test('waiting interrupts a pulse without consuming its four seconds of visible reaction',()=>{const h=harness();let events=window([]);h.update({running:true},chat({calls:[call]}),{events});events=append(events,entry('tool/result',102,{turn:1,message:{source:{callId:'bash'},isError:true}}));h.update({running:true},chat(),{events});const first=h.callbacks.at(-1);h.update({running:true},chat(),{events},{pendingInteraction:{kind:'approval'}});assert.equal(h.states.at(-1),'waiting');assert.equal(h.timers.size,0);first();assert.equal(h.states.at(-1),'waiting');h.update({running:true},chat(),{events});assert.equal(h.states.at(-1),'error');assert.equal(h.delays.at(-1),4000);h.fire();assert.equal(h.states.at(-1),'thinking');});

test('initial admitted pending prompt outranks the previous historical terminal error',()=>{const h=harness();h.update({running:false,pendingSubmissions:[{requestId:'accepted',placement:'transcript'}]},chat({closed:true,reason:'error'}));assert.equal(h.states.at(-1),'queued');});
test('fresh goal block is visible before the native running flag falls and resume restores work',()=>{const h=harness();h.update({running:true},chat(),projection({goal:{goal:{id:'g',phase:'active'}}}));h.update({running:true},chat(),projection({goal:{goal:{id:'g',phase:'blocked'}}}));assert.equal(h.states.at(-1),'blocked');h.update({running:true},chat(),projection({goal:{goal:{id:'g',phase:'active'}}}));assert.equal(h.states.at(-1),'thinking');h.update({running:true},chat(),projection({goal:{goal:{id:'g',phase:'blocked'}}}));h.update({running:true},chat({id:2}),projection({goal:{goal:{id:'g',phase:'blocked'}}}));assert.equal(h.states.at(-1),'thinking','an old blocked goal cannot cover a different manual turn');});
test('reopening a hidden live question retains waiting from public call metadata even when running is false',()=>{const h=harness(),context=projection({userQuestions:{active:[{callId:'bash',state:'open'}]}});h.update({running:false},chat({calls:[call]}),context);assert.equal(h.states.at(-1),'waiting');const g=harness();g.update({running:true},chat({calls:[call]}),context,{pendingInteraction:{kind:'question',callId:'bash'}});g.update({running:false},chat({calls:[call]}),context,{});assert.equal(g.states.at(-1),'waiting');g.update({running:false},chat({closed:true,calls:[call]}),context,{});assert.notEqual(g.states.at(-1),'waiting','closed historical calls cannot reopen a question');});
test('coalesced publication cannot lose a durable failed settlement inserted below the old watermark',()=>{const h=harness();let events=window([]);h.update({running:true},chat(),{events});const chunk=entry('assistant/live-chunk',110,{turn:1,step:1,chunk:{type:'text-delta',text:'reply'}});events=append(events,chunk);h.update({running:true},chat(),{events});const failure=entry('assistant/attempt',103,{turn:1,step:1,stream:[{type:'chunk',chunk:{type:'finish',reason:{kind:'error',failure:{code:'REQUEST'}}}}]});const tail=entry('step/start',111,{turn:1,step:1});events=window([failure,tail],3,{kind:'append',entries:[tail]});h.update({running:true},chat(),{events});assert.equal(h.states.at(-1),'error');h.fire();assert.equal(h.states.at(-1),'thinking');const next=entry('step/end',112,{turn:1,step:1});events=window([failure,tail,next],5,{kind:'append',entries:[next]});h.update({running:true},chat(),{events});assert.equal(h.states.at(-1),'thinking','unseen lower-seq failures must be deduplicated');assert.equal(h.timers.size,0);});
test('a baseline current failure remains silent through later coalesced history reads',()=>{const h=harness();const failure=entry('assistant/attempt',103,{turn:1,step:1,stream:[{type:'chunk',chunk:{type:'finish',reason:{kind:'error'}}}]});let events=window([failure]);h.update({running:true},chat(),{events});const next=entry('step/start',111,{turn:1,step:1});events=window([failure,next],3,{kind:'append',entries:[next]});h.update({running:true},chat(),{events});assert.equal(h.states.at(-1),'thinking');assert.equal(h.timers.size,0);});
