import test from 'node:test';import assert from 'node:assert/strict';import {createReceiptClient} from '../adapters/harness/receipt-client.mjs';import {frameRemote,tick,bashRow} from './receipt-fixture.mjs';
const frame=(rows,extra={})=>({type:'receipts',sessionId:'one',epoch:'epoch',rows,...extra});
test('mount creates an owned namespace and receives only future frozen whitelisted metadata',async()=>{const f=frameRemote(),reader=createReceiptClient(f.ctx);reader.watch('one');await tick();assert.equal(reader.state.getSnapshot().baseline,true);assert.equal(f.mounts.length,1);f.send(frame([bashRow()]));await tick();const snap=reader.state.getSnapshot();assert.equal(snap.baseline,false);assert.deepEqual(snap.rows,[bashRow()]);assert.equal(Object.isFrozen(snap.rows[0]),true);assert.equal(reader.state.getSnapshot(),snap);f.send(frame([bashRow()]));await tick();assert.equal(reader.state.getSnapshot(),snap,'duplicate publication stays referentially stable');await reader.dispose();assert.equal(f.watchers,0);assert.equal(f.releases,1);});
test('each native stream generation must open a fresh baseline before receipts can be accepted',async()=>{const f=frameRemote(),reader=createReceiptClient(f.ctx);reader.watch('one');await tick();f.send(frame([bashRow()]));await tick();assert.equal(reader.state.getSnapshot().rows.length,1);const accepted=f.accepted;f.send({__item:{generation:2,value:frame([bashRow({seq:2})])}});await tick();assert.equal(reader.state.getSnapshot(),undefined,'a new carrier cannot inherit the previous opening');assert.equal(f.accepted,accepted,'unopened carrier must not acknowledge a receipt');f.send({__item:{generation:2,value:{type:'opened',sessionId:'one',epoch:'new',cursor:7}}});await tick();assert.equal(reader.state.getSnapshot().baseline,true);f.send({__item:{generation:2,value:frame([bashRow({seq:6}),bashRow({seq:8})],{epoch:'new'})}});await tick();assert.deepEqual(reader.state.getSnapshot().rows.map(row=>row.seq),[8]);await reader.dispose();});
test('wrong owner, prose-expanded metadata, malformed rows and old epochs never reach activity',async()=>{const f=frameRemote(),reader=createReceiptClient(f.ctx);reader.watch('one');await tick();const initial=reader.state.getSnapshot();f.send(frame([bashRow({sessionId:'two'}),bashRow({exitCode:'3'}),bashRow({content:'private'}),bashRow({turn:0})]));f.send(frame([bashRow()],{epoch:'old'}));f.send({type:'prepend',sessionId:'one',epoch:'epoch',rows:[bashRow()]});await tick();assert.equal(reader.state.getSnapshot(),initial);f.send(frame([{seq:2,version:1,kind:'subagent',sessionId:'one',parentId:'one',childId:'c',runId:'r',provider:'local',local:true,turn:null,stopReason:'error'}]));await tick();assert.equal(reader.state.getSnapshot().rows[0].kind,'subagent');await reader.dispose();});
test('failed mount retries on next standard publication; successful subscriptions are stable',async()=>{const f=frameRemote({mountFailures:1}),reader=createReceiptClient(f.ctx);reader.watch('one');await tick();assert.equal(reader.state.getSnapshot(),undefined);assert.equal(f.mounts.length,1);reader.retry('one');await tick();assert.equal(f.mounts.length,2);assert.equal(f.opened,1);for(let i=0;i<4;i++)reader.retry('one');await tick();assert.equal(f.opened,1);await reader.dispose();});
test('old session leases cannot release the new session and late mount cleanup is owned',async()=>{const f=frameRemote(),reader=createReceiptClient(f.ctx);const old=reader.watch('one');await tick();reader.watch('two');await tick();old();await tick();assert.equal(reader.state.getSnapshot().sessionId,'two');assert.equal(f.watchers,1);await reader.dispose();assert.equal(f.watchers,0);let finish;const late=frameRemote({deferredMount:new Promise(resolve=>finish=resolve)}),other=createReceiptClient(late.ctx);other.watch('one');await tick();const cleanup=other.dispose();finish();await cleanup;await tick();assert.equal(late.releases,1);assert.equal(late.opened,0);});
test('namespace disposal waits for native stream disposal, and official carrier error is used for ended',async()=>{let finish;const f=frameRemote({cleanupGate:new Promise(resolve=>finish=resolve)});class CarrierError extends Error{}const reader=createReceiptClient(f.ctx,CarrierError);reader.watch('one');await tick();assert.ok(f.options[0].ended() instanceof CarrierError);const cleanup=reader.dispose();await tick();assert.equal(f.releases,0,'stream cleanup must finish before namespace teardown');finish();await cleanup;assert.equal(f.releases,1);});
test('client is self-contained and does not acquire history or output services',async()=>{const embed=Function('return ('+createReceiptClient.toString()+')')(),f=frameRemote();Object.defineProperty(f.ctx,'sessions',{get(){throw Error('history not allowed');}});const reader=embed(f.ctx);reader.watch('one');await tick();assert.equal(reader.state.getSnapshot().baseline,true);await reader.dispose();});

test('a standard-publication restart cannot inherit the prior stream opening even if generation numbers repeat',async()=>{
 const f=frameRemote({initialOpening:false}),reader=createReceiptClient(f.ctx);reader.watch('one');await tick();
 f.send({type:'opened',sessionId:'one',epoch:'epoch',cursor:0});await tick();f.send(frame([bashRow()]));await tick();assert.equal(reader.state.getSnapshot().baseline,false);
 f.send({__throw:Error('ordinary source failure')});await tick();assert.equal(reader.state.getSnapshot(),undefined);reader.retry('one');await tick();
 f.send(frame([bashRow({seq:2})]));await tick();assert.equal(reader.state.getSnapshot(),undefined,'same generation id in a new stream must reopen');
 f.send({type:'opened',sessionId:'one',epoch:'epoch',cursor:2});await tick();assert.equal(reader.state.getSnapshot().baseline,true);await reader.dispose();
});

test('React-coalesced separate frames preserve an earlier failure until the state consumer observes it',async()=>{
 const f=frameRemote(),reader=createReceiptClient(f.ctx);reader.watch('one');await tick();
 f.send(frame([bashRow()]));await tick();f.send(frame([bashRow({seq:2,exitCode:0})]));await tick();
 assert.deepEqual(reader.state.getSnapshot().rows.map(row=>[row.seq,row.exitCode]),[[1,3],[2,0]],'later successful operation cannot overwrite an unconsumed failure frame');
 await reader.dispose();
});

test('Cordis may return a new trace proxy for the same required remote service on every get',async()=>{
 const f=frameRemote(),lookup=f.ctx.get;f.ctx.get=key=>key==='remote'?new Proxy(f.remote,{}):lookup(key);
 const reader=createReceiptClient(f.ctx);reader.watch('one');await tick();assert.equal(f.opened,1,'fresh Cordis service proxies must not block stream admission');assert.equal(reader.state.getSnapshot().baseline,true);
 reader.retry('one');await tick();assert.equal(f.mounts.length,1);assert.equal(f.opened,1);await reader.dispose();
});
