import test from 'node:test';import assert from 'node:assert/strict';import {mountReceiptHost} from '../adapters/harness/receipt-host.mjs';
function fixture({agents,carrierKeyOf}={}) {
 const listeners=new Map(),provided=new Map(),contributions=[];let serviceReleased=0,typeReleased=0;
 const ctx={agents,on(name,fn){if(!listeners.has(name))listeners.set(name,new Set());listeners.get(name).add(fn);return()=>listeners.get(name)?.delete(fn);},provide(name,service){provided.set(name,service);return()=>{serviceReleased++;provided.delete(name);};},typert:{register(value){contributions.push(value);return()=>{typeReleased++;};}}};
 const emit=(name,...args)=>{for(const fn of [...listeners.get(name)||[]])fn(...args);};
 const session={id:'one',append(){throw Error('receipt must never write native session');}},agent={id:'one',session};const host=mountReceiptHost(ctx,carrierKeyOf);
 const start=(turn=4,callId='bash')=>{emit('session/event',session,Object.freeze({type:'turn/start',seq:100,data:Object.freeze({turn})}));emit('session/event',session,Object.freeze({type:'tool/call',seq:101,data:Object.freeze({turn,step:1,callId,name:'bash'})}));};
 const result=(value,{name='bash',callId='bash',rootCallId=callId,subject=agent,isError=false}={})=>{const exec=Object.freeze({name,callId,rootCallId,agent:subject});const canonical=Object.freeze({isError,value:value===null?null:Object.freeze(value),get content(){throw Error('never read rendered content');}});emit('tools/result',exec,canonical);return{exec,canonical};};
 const open=async(owner='one')=>{const abort=new AbortController(),iterator=host.service.follow({sessionId:owner},abort.signal),baseline=(await iterator.next()).value;return{baseline,iterator,async next(){return(await iterator.next()).value;},async close(){abort.abort();await iterator.return();}};};
 return{ctx,host,session,agent,start,result,emit,open,listeners,contributions,provided,get serviceReleased(){return serviceReleased;},get typeReleased(){return typeReleased;},get listenerCount(){return[...listeners.values()].reduce((sum,set)=>sum+set.size,0);},callback(name){return[...listeners.get(name)||[]][0];}};
}
const dto=(extra={})=>({kind:'foreground',exitCode:0,timedOut:false,signal:null,aborted:false,...extra});
async function cursor(f){const view=await f.open();const value=view.baseline.cursor;await view.close();return value;}
test('foreground code 0/3, timeout and signal yield one frozen whitelisted transient receipt each',async()=>{for(const values of [dto(),dto({exitCode:3}),dto({timedOut:true}),dto({signal:'SIGTERM',exitCode:null})]){const f=fixture(),view=await f.open();f.start();const{exec,canonical}=f.result({...values,stdout:{text:'private'},stderr:{text:'private'},extra:'private'});const frame=await view.next();assert.equal(frame.type,'receipts');assert.deepEqual(frame.rows,[{seq:1,version:1,kind:'bash',sessionId:'one',turn:4,callId:'bash',exitCode:values.exitCode,timedOut:values.timedOut,signal:values.signal}]);assert.ok(Object.isFrozen(frame.rows[0]));f.emit('tools/result',exec,canonical);assert.equal(await cursor(f),1,'duplicate publication is ignored');await view.close();f.host.dispose();}});
test('requires exact session and actual current started call, including nested root correlation',async()=>{const f=fixture();f.start();f.result(dto({exitCode:3}),{callId:'unknown'});f.result(dto({exitCode:3}),{subject:{id:'two',session:{id:'one'}}});assert.equal(await cursor(f),0);const view=await f.open();f.result(dto({exitCode:3}),{callId:'nested-bash',rootCallId:'bash'});assert.equal((await view.next()).rows[0].callId,'nested-bash');f.emit('session/event',f.session,{type:'turn/end',data:{turn:4}});f.result(dto({exitCode:3}));assert.equal(await cursor(f),1);await view.close();f.host.dispose();});
test('unknown, promoted/background, malformed, aborted and infrastructure errors are ignored',async()=>{for(const value of [{kind:'background',jobId:'job'},{kind:'promoted',jobId:'job'},null,{kind:'foreground'},{...dto(),exitCode:'3'},{...dto(),aborted:true}]){const f=fixture();f.start();assert.doesNotThrow(()=>f.result(value));assert.equal(await cursor(f),0);f.host.dispose();}const f=fixture();f.start();f.result(dto({exitCode:3}),{isError:true});f.result(dto({exitCode:3}),{name:'other'});assert.equal(await cursor(f),0);f.host.dispose();});
test('official service binding and reflection match; abort and host disposal unblock pending iterators',async()=>{const f=fixture();assert.equal(f.provided.get('deskskinReceipt'),f.host.service);assert.equal(f.host.service.typertRemote.service,f.host.service);assert.deepEqual(f.contributions[0].invocations,[f.host.descriptor]);const view=await f.open();const pending=view.iterator.next();await view.close();assert.equal((await pending).done,true);const other=await f.open();const waiting=other.iterator.next();f.host.dispose();assert.equal((await waiting).done,true);assert.equal(f.listenerCount,0);assert.equal(f.serviceReleased,1);assert.equal(f.typeReleased,1);f.host.dispose();});
test('host embeds without imports or closures and fiber cleanup blocks queued observers',async()=>{const embed=Function('return ('+mountReceiptHost.toString()+')')();const callbacks=new Map();let cleanup;const host=embed({on(name,fn){callbacks.set(name,fn);return()=>callbacks.delete(name);},effect(setup){cleanup=setup();return()=>cleanup?.();}});const old=callbacks.get('tools/result');assert.equal(typeof cleanup,'function');cleanup();assert.equal(callbacks.size,0);assert.doesNotThrow(()=>old({name:'bash'},{value:{get exitCode(){throw Error('disposed must not read');}}}));host.dispose();});
test('scope helper ties child metadata to the exact started parent, without reading its output',async()=>{const keys=new WeakMap(),f=fixture({carrierKeyOf:value=>keys.get(value)}),carrier={},wrong={};keys.set(carrier,f.agent);keys.set(wrong,{id:'other',session:{id:'other'}});const view=await f.open();f.start(1);const run={runId:'run',id:'child',provider:'local',local:true};f.callback('subagent/start').call(carrier,Object.freeze(run));const finish=Object.freeze({...run,stopReason:'error',get lastAssistantMessage(){throw Error('never read child output');}});f.callback('subagent/end').call(wrong,finish);assert.equal(await cursor(f),0);f.callback('subagent/end').call(carrier,finish);assert.deepEqual((await view.next()).rows,[{seq:1,version:1,kind:'subagent',sessionId:'one',parentId:'one',childId:'child',runId:'run',provider:'local',local:true,turn:1,stopReason:'error'}]);f.callback('subagent/end').call(carrier,finish);assert.equal(await cursor(f),1);await view.close();f.host.dispose();});
test('typed child reasons include completion/cancel without inventing unmatched or malformed outcomes',async()=>{for(const reason of ['completed','aborted','max-tokens','refusal']){let parent;const carrier={},f=fixture({carrierKeyOf:value=>value===carrier?parent:undefined});parent=f.agent;const run={runId:'r',id:'c',provider:'remote',local:false};f.callback('subagent/end').call(carrier,{...run,stopReason:reason});assert.equal(await cursor(f),0);f.callback('subagent/start').call(carrier,run);f.callback('subagent/end').call(carrier,{...run,id:'wrong',stopReason:reason});assert.equal(await cursor(f),0);const view=await f.open();f.callback('subagent/end').call(carrier,{...run,stopReason:reason});const row=(await view.next()).rows[0];assert.equal(row.turn,null);assert.equal(row.stopReason,reason);await view.close();f.host.dispose();}});
test('subagent observer exceptions, unknown reason and queued callbacks stay contained',async()=>{let parent;const good={},bad={},f=fixture({carrierKeyOf:value=>{if(value===bad)throw Error('carrier unavailable');return value===good?parent:undefined;}});parent=f.agent;const run={runId:'r',id:'c',provider:'local',local:true},start=f.callback('subagent/start'),end=f.callback('subagent/end');assert.doesNotThrow(()=>start.call(bad,run));start.call(good,run);assert.doesNotThrow(()=>end.call(good,{...run,stopReason:'future-unknown'}));assert.equal(await cursor(f),0);f.host.dispose();assert.doesNotThrow(()=>start.call(good,{get runId(){throw Error('disposed must not read');}}));assert.doesNotThrow(()=>end.call(good,{get runId(){throw Error('disposed must not read');}}));});
test('local registry proves runtime parent and child may detach before its terminal edge',async()=>{const live=new Map();let parent;const agents={get:id=>live.get(id),isOwnedBy:(id,owner)=>id==='child'&&owner===parent};const f=fixture({agents});parent=f.agent;live.set('one',parent);live.set('child',{id:'child',session:{id:'child',header:{parentSession:'one'}}});const view=await f.open(),run={runId:'r',id:'child',provider:'local',local:true};f.callback('subagent/start')(run);live.delete('child');f.callback('subagent/end')({...run,stopReason:'error'});assert.equal((await view.next()).rows[0].parentId,'one');await view.close();f.host.dispose();});
test('lineage alone, unrelated owner, remote child and replaced parent cannot claim local receipts',async()=>{const live=new Map();let parent,owned=false;const agents={get:id=>live.get(id),isOwnedBy:(id,owner)=>owned&&id==='child'&&owner===parent};const f=fixture({agents});parent=f.agent;live.set('one',parent);live.set('child',{id:'child',session:{id:'child',header:{parentSession:'one'}}});const start=f.callback('subagent/start'),end=f.callback('subagent/end'),run={runId:'r',id:'child',provider:'local',local:true};start(run);end({...run,stopReason:'error'});assert.equal(await cursor(f),0);owned=true;start({...run,runId:'remote',local:false});end({...run,runId:'remote',local:false,stopReason:'error'});assert.equal(await cursor(f),0);start(run);live.set('one',{id:'one',session:f.session});end({...run,stopReason:'error'});assert.equal(await cursor(f),0);f.host.dispose();});
test('opening a later subscriber never replays receipts emitted before it joined',async()=>{const f=fixture();f.start();f.result(dto({exitCode:3}));const view=await f.open();assert.equal(view.baseline.cursor,1);f.result(dto({exitCode:0}));assert.equal((await view.next()).rows[0].seq,2);await view.close();f.host.dispose();});
