// Generated by scripts/update-action-focus.mjs from inspected artwork.
export const ACTION_FOCUS = {
  "serene": {
    "states": {
      "idle": {
        "focus": "50.38% 4.01%",
        "scale": "480% auto"
      },
      "thinking": {
        "focus": "42.17% 2.97%",
        "scale": "480% auto"
      },
      "working": {
        "focus": "37.37% 15.16%",
        "scale": "480% auto"
      },
      "answering": {
        "focus": "59.09% 4.25%",
        "scale": "480% auto"
      },
      "parallel": {
        "focus": "50.38% 4.25%",
        "scale": "480% auto"
      },
      "compacting": {
        "focus": "43.22% 7.36%",
        "scale": "480% auto"
      },
      "retrying": {
        "focus": "36.23% 3.90%",
        "scale": "480% auto"
      },
      "waiting": {
        "focus": "50.13% 3.90%",
        "scale": "480% auto"
      },
      "complete": {
        "focus": "48.11% 5.17%",
        "scale": "480% auto"
      },
      "error": {
        "focus": "34.84% 3.78%",
        "scale": "480% auto"
      },
      "queued": {
        "focus": "56.69% 7.03%",
        "scale": "480% auto"
      },
      "connecting": {
        "focus": "50.88% 11.68%",
        "scale": "480% auto"
      },
      "disconnected": {
        "focus": "47.47% 5.87%",
        "scale": "480% auto"
      },
      "stopped": {
        "focus": "45.83% 3.20%",
        "scale": "480% auto"
      },
      "paused": {
        "focus": "47.22% 7.61%",
        "scale": "480% auto"
      },
      "blocked": {
        "focus": "50.38% 4.25%",
        "scale": "480% auto"
      },
      "writing": {
        "focus": "37.17% 10.99%",
        "scale": "480% auto"
      },
      "reading": {
        "focus": "41.98% 9.85%",
        "scale": "480% auto"
      },
      "searching": {
        "focus": "32.73% 6.38%",
        "scale": "480% auto"
      },
      "delegating": {
        "focus": "44.57% 5.92%",
        "scale": "480% auto"
      },
      "executing": {
        "focus": "46.46% 11.21%",
        "scale": "480% auto"
      }
    },
    "intro": {
      "away": {
        "focus": "43.56% 3.90%",
        "scale": "480% auto"
      },
      "turning": {
        "focus": "43.68% 4.01%",
        "scale": "480% auto"
      },
      "front-neutral": {
        "focus": "50.38% 4.01%",
        "scale": "480% auto"
      },
      "front-smile": {
        "focus": "50.38% 4.01%",
        "scale": "480% auto"
      }
    }
  },
  "maid": {
    "states": {
      "idle": {
        "focus": "50.00% 7.38%",
        "scale": "480% auto"
      },
      "thinking": {
        "focus": "48.74% 6.34%",
        "scale": "480% auto"
      },
      "working": {
        "focus": "51.64% 21.20%",
        "scale": "480% auto"
      },
      "answering": {
        "focus": "47.47% 6.57%",
        "scale": "480% auto"
      },
      "parallel": {
        "focus": "50.00% 6.80%",
        "scale": "480% auto"
      },
      "compacting": {
        "focus": "51.73% 8.42%",
        "scale": "480% auto"
      },
      "retrying": {
        "focus": "48.74% 7.85%",
        "scale": "480% auto"
      },
      "waiting": {
        "focus": "49.75% 6.10%",
        "scale": "480% auto"
      },
      "complete": {
        "focus": "50.76% 7.15%",
        "scale": "480% auto"
      },
      "error": {
        "focus": "47.98% 7.26%",
        "scale": "480% auto"
      },
      "queued": {
        "focus": "49.62% 7.85%",
        "scale": "480% auto"
      },
      "connecting": {
        "focus": "47.73% 12.72%",
        "scale": "480% auto"
      },
      "disconnected": {
        "focus": "49.49% 7.85%",
        "scale": "480% auto"
      },
      "stopped": {
        "focus": "48.36% 7.03%",
        "scale": "480% auto"
      },
      "paused": {
        "focus": "61.49% 9.35%",
        "scale": "480% auto"
      },
      "blocked": {
        "focus": "48.74% 7.26%",
        "scale": "480% auto"
      },
      "writing": {
        "focus": "50.25% 12.35%",
        "scale": "480% auto"
      },
      "reading": {
        "focus": "41.49% 11.74%",
        "scale": "480% auto"
      },
      "searching": {
        "focus": "44.82% 7.89%",
        "scale": "480% auto"
      },
      "delegating": {
        "focus": "50.86% 6.60%",
        "scale": "480% auto"
      },
      "executing": {
        "focus": "56.32% 19.23%",
        "scale": "480% auto"
      }
    },
    "intro": {
      "away": {
        "focus": "43% 5%",
        "scale": "480% auto"
      },
      "turning": {
        "focus": "47% 6.5%",
        "scale": "480% auto"
      },
      "front-neutral": {
        "focus": "50% 8%",
        "scale": "480% auto"
      },
      "front-smile": {
        "focus": "50% 8%",
        "scale": "480% auto"
      }
    }
  },
  "maid_chibi": {
    "states": {
      "idle": {
        "focus": "48.44% 23.75%",
        "scale": "280% auto"
      },
      "answering": {
        "focus": "50.78% 23.75%",
        "scale": "280% auto"
      },
      "parallel": {
        "focus": "50.78% 23.75%",
        "scale": "280% auto"
      },
      "complete": {
        "focus": "50.62% 24.41%",
        "scale": "280% auto"
      },
      "thinking": {
        "focus": "47.04% 19.02%",
        "scale": "280% auto"
      },
      "working": {
        "focus": "43.78% 36.48%",
        "scale": "280% auto"
      },
      "error": {
        "focus": "49.53% 22.57%",
        "scale": "280% auto"
      },
      "compacting": {
        "focus": "57.14% 22.74%",
        "scale": "280% auto"
      },
      "retrying": {
        "focus": "48.44% 26.11%",
        "scale": "280% auto"
      },
      "waiting": {
        "focus": "51.56% 21.78%",
        "scale": "280% auto"
      },
      "queued": {
        "focus": "50.31% 21.52%",
        "scale": "280% auto"
      },
      "connecting": {
        "focus": "51.56% 25.06%",
        "scale": "280% auto"
      },
      "disconnected": {
        "focus": "49.69% 23.62%",
        "scale": "280% auto"
      },
      "stopped": {
        "focus": "49.69% 21.78%",
        "scale": "280% auto"
      },
      "paused": {
        "focus": "61.67% 27.03%",
        "scale": "280% auto"
      },
      "blocked": {
        "focus": "50.78% 21.78%",
        "scale": "280% auto"
      },
      "writing": {
        "focus": "46.96% 22.49%",
        "scale": "280% auto"
      },
      "reading": {
        "focus": "45.75% 21.63%",
        "scale": "280% auto"
      },
      "searching": {
        "focus": "45.75% 19.49%",
        "scale": "280% auto"
      },
      "delegating": {
        "focus": "51.37% 18.55%",
        "scale": "280% auto"
      },
      "executing": {
        "focus": "53.11% 27.03%",
        "scale": "280% auto"
      }
    },
    "intro": {
      "away": {
        "focus": "41.44% 22.83%",
        "scale": "280% auto"
      },
      "turning": {
        "focus": "43.00% 22.83%",
        "scale": "280% auto"
      },
      "front-neutral": {
        "focus": "50.00% 22.70%",
        "scale": "280% auto"
      },
      "front-smile": {
        "focus": "50.00% 22.70%",
        "scale": "280% auto"
      }
    }
  }
};
